version: "v0.0.1"
services:
  postgresDB:
    image: postgres
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  express-app:
    image: express-js-server-app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgresDB
    ports:
      - ${PORT}:${PORT}
